name       : dmenu
version    : '4.7'
release    : 2
source     :
    - http://dl.suckless.org/tools/dmenu-4.7.tar.gz : a75635f8dc2cbc280deecb906ad9b7594c5c31620e4a01ba30dc83984881f7b9
license    : MIT
component  : desktop
summary    : dmenu is a dynamic menu for X, originally designed for dwm.
description: |
    dmenu is a dynamic menu for X, originally designed for dwm.
builddeps  :
    - pkgconfig(freetype2)
    - pkgconfig(xft)
    - pkgconfig(xinerama)
build      : |
    %make X11INC=/usr/include/X11 X11LIB=/usr/lib/X11 FREETYPEINC=/usr/include/freetype2
install    : |
    %make_install PREFIX=/usr
