name       : dmenu
version    : '4.9'
release    : 3
source     :
    - https://dl.suckless.org/tools/dmenu-4.9.tar.gz : b3971f4f354476a37b2afb498693649009b201550b0c7c88e866af8132b64945
license    : MIT
component  : desktop
summary    : dmenu is a dynamic menu for X, originally designed for dwm.
description: |
    dmenu is a dynamic menu for X, originally designed for dwm.
builddeps  :
    - pkgconfig(freetype2)
    - pkgconfig(xft)
    - pkgconfig(xinerama)
setup      : |
    %apply_patches
build      : |
    %make X11INC=/usr/include/X11 X11LIB=/usr/lib/X11 FREETYPEINC=/usr/include/freetype2
install    : |
    %make_install PREFIX=/usr
