name       : dmenu
version    : 4.6
release    : 1
source     :
    - http://dl.suckless.org/tools/dmenu-4.6.tar.gz : 4a7a24008a621c3cd656155ad91ab8136db8f0d3b9ec56dafeec518cabda96b3
license    : MIT
component  : desktop
summary    : dmenu is a dynamic menu for X, originally designed for dwm.
description: |
    dmenu is a dynamic menu for X, originally designed for dwm.
builddeps  :
    - pkgconfig(freetype2)
    - pkgconfig(xft)
    - pkgconfig(xinerama)
build      : |
    %make X11INC=/usr/include/X11 X11LIB=/usr/lib/X11 FREETYPEINC=/usr/include/freetype2
install    : |
    %make_install PREFIX=/usr
